### ISSUE TITLE
[Error] - Server crash on startup while using mod.

### ISSUE THREAD

**Issue by vn-vna** [aitecraft/shareenderchest#6]
I have tried installing this mod on my server. It worked as expected a few first minutes but then the server is crashed an can't be started up again. This is what I see on the server's terminal when it was crashed.

```
...
[00:12:43] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.class_2487 net.minecraft.class_2507.method_10629(java.io.InputStream)'
        at me.glitch.aitecraft.shareenderchest.ShareEnderChest.onServerStarted(ShareEnderChest.java:58) ~[shareenderchest-1.6.0.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.2.2+78d798af4f-694f1a2356fcf3bb.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zlp000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2414) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:654) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[00:12:44] [Server thread/ERROR]: This crash report has been saved to: /home/vnvna/Downloads/mc/./crash-reports/crash-2023-12-25_00.12.44-server.txt
[00:12:44] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "me.glitch.aitecraft.shareenderchest.SharedInventory.getList(net.minecraft.class_2371)" because "me.glitch.aitecraft.shareenderchest.ShareEnderChest.sharedInventory" is null
        at me.glitch.aitecraft.shareenderchest.ShareEnderChest.saveInventory(ShareEnderChest.java:77) ~[shareenderchest-1.6.0.jar:?]
        at me.glitch.aitecraft.shareenderchest.ShareEnderChest.onServerStopping(ShareEnderChest.java:90) ~[shareenderchest-1.6.0.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:63) ~[fabric-lifecycle-events-v1-2.2.2+78d798af4f-694f1a2356fcf3bb.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zlp000$fabric-lifecycle-events-v1$beforeShutdownServer(MinecraftServer.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:542) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:718) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[00:12:44] [Server thread/INFO]: Thread RCON Listener stopped
```

This is my crash report file's content
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-12-25 00:21:49
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.class_2487 net.minecraft.class_2507.method_10629(java.io.InputStream)'
	at me.glitch.aitecraft.shareenderchest.ShareEnderChest.onServerStarted(ShareEnderChest.java:58)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$zlp000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2414)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:654)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:840)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (amd64) version 6.6.7-arch1-1
	Java Version: 17.0.9, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7954495488 bytes (7585 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600H with Radeon Graphics
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 4
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: SVGA II Adapter
	Graphics card #0 vendor: VMware (0x15ad)
	Graphics card #0 VRAM (MB): 128.00
	Graphics card #0 deviceId: 0x0405
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7908.37
	Virtual memory used (MB): 2760.91
	Swap memory total (MB): 3954.00
	Swap memory used (MB): 423.25
	JVM Flags: 2 total; -Xms8G -Xmx8G
	Fabric Mods: 
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.38
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.38
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.38
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.38
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.38
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.38
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.38
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.38
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.38
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.38
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.38
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.38
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.38
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.38
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.38
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.38
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.38
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.38
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.38
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.38
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		collective: Collective 7.23
		debugify: Debugify 1.20.4+1.0
		fabric-api: Fabric API 0.91.3+1.20.4
			fabric-api-base: Fabric API Base 0.4.35+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.45+78d798af4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.19+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.17+78d798af4f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.28+4ced05924f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.14+78d798af4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.29+78d798af4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+78d798af4f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.7+78d798af4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.6+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.15+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.13+78d798af4f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.15+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.50+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.6+78d798af4f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		ferritecore: FerriteCore 6.0.3
		healingcampfire: Healing Campfire 5.3
		incendium: Incendium 5.3.4
		java: OpenJDK 64-Bit Server VM 17
		ksyxis: Ksyxis 1.2.2
		letmedespawn: Let Me Despawn 1.2.0
		lithium: Lithium 0.12.1
		mine-spawners: mine-spawners 1.0
		minecraft: Minecraft 1.20.4
		modernfix: ModernFix 5.11.0+mc1.20.4
		mr_mine_treasure: Mine Treasure 1.3.3
		noisium: Noisium 1.0.2+mc1.20.x
		quickshulker: Quick Shulker 1.4.0-1.20
			kyrptconfig: Kyrpt Config 1.5.4-1.20
			shulkerutils: shulkerutils 1.0.4-1.19
		shareenderchest: ShareEnderChest 1.6.0
		slumber: Slumber 1.2.0
		treeharvester: Tree Harvester 8.4
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, fabric, file/spellbound-weapons-v4.0.5j.zip, file/tpa v2.3.6 (MC 1.20-1.20.4).zip, file/waypoints-vanilla-v1.0-beta.4.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

I tried deleting file `shareenderchest.sav` and then the server sucessfully started again.

**Comment by kripesh101** [comment]
The mod has finally been updated to support 1.20.4, it should work now! [Latest version is on Modrinth](https://modrinth.com/mod/share-ender-chest/version/1.6.1)

**Comment by vn-vna** [comment]
> The mod has finally been updated to support 1.20.4, it should work now! [Latest version is on Modrinth](https://modrinth.com/mod/share-ender-chest/version/1.6.1)

Thank you for the patch. I'm gonna try it now ╰(*°▽°*)╯
